---
title: "Simulated Grouped Hyper Data Frame"
author: Tingting Zhan
date: today
format: 
  html:
    page-layout: full
    html-math-method: katex
    link-external-icon: true
    link-external-newwindow: true
number-sections: true
toc: true
toc-location: left
toc-depth: 4
toc-title: ''
editor: source
bibliography: groupedHyperframe.random.bib
knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---


The complete vignette of R [@R] package **`groupedHyperframe.random`** (v`r packageVersion('groupedHyperframe.random')`) 

> <https://tingtingzhan.quarto.pub/groupedhyperframe/random>

documents

-   the simulation of superimposed (marked) point-pattern objects via *vectorized parameterization*;
-   the simulation of grouped hyper data frame via *matrix parameterization*.

The complete vignette exceeds the file size limit allowed on [CRAN](https://cran.r-project.org/package=groupedHyperframe.random).  


# Prerequisite

## Environment

Package **`groupedHyperframe.random`** (v`r packageVersion('groupedHyperframe.random')`) requires R version 4.5.0 (released 2025-04-11) or higher. Details are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#sec-envir).


## Installation

Packages **`groupedHyperframe.random`** (v`r packageVersion('groupedHyperframe.random')`) and **`groupedHyperframe`** (v`r packageVersion('groupedHyperframe')`) can be installed using the following command.


```{r}
#| eval: false
utils::install.packages('groupedHyperframe')
utils::install.packages('groupedHyperframe.random')
```




## Enhancement & 

Package **`groupedHyperframe.random`** (v`r packageVersion('groupedHyperframe.random')`) `Enhances` the **`spatstat.*`** family of packages [@spatstat15; @spatstat05], especially **`spatstat.random`**. Details are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#groupedhyperframe.random).



## Dependency


The dependencies of package **`groupedHyperframe`** are detailed in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/about.html#groupedhyperframe-1).

Package **`groupedHyperframe`** requires the *development versions* of the **`spatstat.*`** family of packages. Installation instructions are provided in the [book chapter](https://tingtingzhan.quarto.pub/groupedhyperframe/appendix/dev.html).


<!--
# Acknowledgement

Most of this work was undertaken during Tingting Zhan’s leisure hours, with limited support from National Institutes of Health, U.S. Department of Health and Human Services grants

-   R01CA222847 ([I. Chervoneva](https://orcid.org/0000-0002-9104-4505), [T. Zhan](https://orcid.org/0000-0001-9971-4844), and [H. Rui](https://orcid.org/0000-0002-8778-261X))
-   R01CA253977 (H. Rui and I. Chervoneva).
-->



# References {.appendix}

::: {#refs}
:::
